# docker-compose.yml

services:
  app:
    # Construye la imagen usando el Dockerfile en la carpeta ./app
    build: ./app
    ports:
      # Mapea el puerto 5000 del contenedor al 5000 del runner
      - "5000:5000"
    # El servicio 'app' no se iniciará hasta que el servicio 'mysql' esté saludable
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    container_name: lab-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      # Corregí el nombre de usuario aquí para que coincida con tu app.py
      # Antes decía 'usercle'
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5